### ISSUE TITLE
Some results from search 404

### ISSUE THREAD

**Issue by jonas-jonas** [ory/docs#1336] opened 2023-03-22 14:52 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A few links in the search 404.

### Reproducing the bug

1. Search for `id_token`
2. Select something from the `Concepts` section
3. See 404

### Version

live

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by fbolton** [comment] 2023-03-30 11:51
@kmherrmann already spotted this problem and brought it to our attention. For some reason, the Algolia search engine has got stale URLs in its database. Algolia is scheduled to another crawl of our docs site tonight. Hopefully, that will fix the problem.

**Comment by vinckr** [comment] 2023-08-03 08:45
@jonas-jonas 
Can you check if this is still an issue? 
I tried it out right now and it seems all the stale URLs are gone from search, I only got working documents.

**Comment by kmherrmann** [comment] 2023-08-03 08:52
i can't reproduce anymore, closing

**Closed by kmherrmann** 2023-08-03 08:52 UTC
Labels: bug
